const categories=[['Cà phê','Coffee'],['Trà & trái cây','Tea & fruit'],['Vị Nhật Bản','Japanese drinks'],['Ăn vặt','Snacks'],['Bia','Beer']];
const menus=[[
['Cà phê đen','Black coffee',39],['Cà phê muối','Salt coffee',49],['Cà phê sữa tươi','Coffee with fresh milk',49],['Bạc xỉu','Vietnamese milk coffee',49]
],[['Trà vải chanh dây','Lychee & passion fruit tea',55],['Trà sữa Olong','Oolong milk tea',55],['Trà sữa đào','Peach milk tea',55],['Trà Atiso đỏ','Hibiscus tea',55],['Trà chanh đậu biếc','Butterfly pea & lime tea',49],['Trà sen vàng','Golden lotus tea',59],['Trà đào dầm','Crushed peach tea',49],['Trà xoài','Mango tea',49],['Trà dâu','Strawberry tea',49],['Trà ổi','Guava tea',49],['Trà mãng cầu','Soursop tea',55],['Trà sen lá dứa','Lotus & pandan tea',59]],
[['Matcha sữa','Matcha latte',59],['Trà sữa Kirin','Kirin milk tea',55],['Trà sữa Sakura','Sakura milk tea',59],['Soda mơ','Apricot soda',55],['Trà lúa mạch (không đường)','Barley tea (unsweetened)',39],['Trà sữa lúa mạch','Barley milk tea',55],['Nước ép sơ ri thanh long','Acerola & dragon fruit juice',55],['Nước ép sơ ri chanh dây','Acerola & passion fruit juice',55]],
[['Bánh tráng chấm','Rice paper with dipping sauce',10],['Khô gà nhà làm','House-made dried chicken',50],['Đậu phộng rang','Roasted peanuts',25],['Hướng dương','Sunflower seeds',25],['Khoai tây chiên','French fries',35],['Bò viên chiên','Fried beef balls',50]],
[['Bia Blanc','Blanc beer',49],['Bia Corona','Corona beer',45],['Bia Hoegaarden','Hoegaarden beer',49],['Bia Stella Artois','Stella Artois beer',59],['Bia Budweiser','Budweiser beer',39],['Bia Leffee Brown','Leffee Brown beer',69]]];
let lang='vi',category=0;const tabs=document.querySelector('.tabs'),items=document.getElementById('menu-items');
function renderMenu(){tabs.innerHTML=categories.map((c,i)=>`<button role="tab" id="tab-${i}" aria-controls="menu-items" aria-selected="${i===category}" tabindex="${i===category?0:-1}" class="${i===category?'active':''}" data-category="${i}">${c[lang==='vi'?0:1]}</button>`).join('');items.setAttribute('aria-labelledby',`tab-${category}`);items.innerHTML=menus[category].map(row=>`<div class="menu-item"><div class="item-name">${row[lang==='vi'?0:1]}${lang==='en'?`<small>${row[0]}</small>`:''}</div><span class="price">${row[2]}.000 <small>₫</small></span></div>`).join('');}
tabs.addEventListener('click',e=>{const b=e.target.closest('button');if(b){category=Number(b.dataset.category);renderMenu();document.getElementById(`tab-${category}`).focus();}});
tabs.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();category=e.key==='Home'?0:e.key==='End'?categories.length-1:(category+(e.key==='ArrowRight'?1:-1)+categories.length)%categories.length;renderMenu();document.getElementById(`tab-${category}`).focus();}});
function setLanguage(next){lang=next;document.documentElement.lang=lang;document.querySelectorAll('[data-vi]').forEach(el=>{el.innerHTML=el.dataset[lang]});['vi','en'].forEach(l=>{document.getElementById(l).classList.toggle('active',l===lang);document.getElementById(l).setAttribute('aria-pressed',String(l===lang));});renderMenu();requestAnimationFrame(sizeMenu);}
document.getElementById('vi').onclick=()=>setLanguage('vi');document.getElementById('en').onclick=()=>setLanguage('en');const dialog=document.getElementById('menu-dialog');document.getElementById('original').onclick=()=>dialog.showModal();document.getElementById('close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});renderMenu();

function sizeMenu(){
 if(document.getElementById('menu').hidden)return;
 const probe=document.createElement('div');probe.className='menu-grid menu-measure';probe.style.width=items.getBoundingClientRect().width+'px';document.body.append(probe);
 let maxHeight=0;
 for(const list of menus){for(const language of ['vi','en']){probe.innerHTML=list.map(row=>`<div class="menu-item"><div class="item-name">${row[language==='vi'?0:1]}${language==='en'?`<small>${row[0]}</small>`:''}</div><span class="price">${row[2]}.000 <small>₫</small></span></div>`).join('');maxHeight=Math.max(maxHeight,probe.getBoundingClientRect().height);}}
 probe.remove();items.style.height=Math.ceil(maxHeight)+'px';
}
function showPage(){const key=location.hash.slice(1);const page=['menu','staff'].includes(key)?key:'home';document.querySelectorAll('.page-view').forEach(el=>el.hidden=el.id!==page);document.querySelectorAll('[data-page]').forEach(el=>{if(el.dataset.page===page)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});sizeMenu();if(key!=='visit'&&key!=='story')window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('hashchange',showPage);window.addEventListener('resize',sizeMenu);document.fonts.ready.then(sizeMenu);showPage();
